name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
    volumes:
      - hl-data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - hl-data:/home/hluser/hl/data

  syncer:
    restart: unless-stopped
    build: ./syncer
    volumes:
      - hl-data:/home/hluser/hl/data
    environment:
      - FILLS_DIR=/home/hluser/hl/data/node_fills/hourly
      - STATE_FILE=/home/hluser/hl/data/syncer_state.json
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_DB=hyperliquid
      - CLICKHOUSE_TABLE=fills
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - BATCH_SIZE=100
      - BATCH_TIMEOUT=5s


volumes:
  hl-data:
    driver: local
