name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    ports:
      - "4000-4010:4000-4010"
    volumes:
      - hl-data:/home/hluser/hl/data

  pruner:
    restart: unless-stopped
    build: ./pruner
    volumes:
      - hl-data:/home/hluser/hl/data

  fileserver:
    restart: unless-stopped
    image: nginx:alpine
    network_mode: host
    volumes:
      - hl-data:/data
      - ./fileserver/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  hl-data:
    driver: local
